defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *defaults
  database: sprofile_dev
  host: localhost

test:
  <<: *defaults
  database: sprofile_test
  host: localhost

production:
  encoding: utf8